# Generated by Django 4.2.5 on 2024-06-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('pax', models.CharField(max_length=10)),
                ('date', models.DateField(max_length=20)),
                ('activity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('WorkersId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('sec_name', models.CharField(max_length=25)),
            ],
        ),
    ]
