# Generated by Django 4.2.5 on 2024-06-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BNB', '0002_customer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting', 'Waiting')], default='waiting', max_length=10),
        ),
    ]
